"""Secret-free, server-routed Audio Overview UI assets.

The browser receives only an informational capability record.  It never receives
provider credentials and never contacts a provider directly.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from html import escape
import json
from typing import Mapping

SCRIPT_MODEL = "gemini-3.1-pro-preview"
TTS_MODEL = "gemini-2.5-flash-preview-tts"


@dataclass(frozen=True)
class AudioCapabilityV1:
    schema: str = "AudioCapabilityV1"
    feature: str = "audio_overview"
    provider: str = "gemini"
    state: str = "UNAVAILABLE"
    reason: str = "GEMINI_AUTH_UNAVAILABLE"
    model: str | None = None

    def to_dict(self) -> dict:
        return asdict(self)


def derive_audio_capability(*, auth: str | None, models: Mapping[str, str] | None,
                            safe_root: bool = True) -> AudioCapabilityV1:
    """Derive capability using configuration only; this deliberately has no I/O."""
    if not safe_root:
        return AudioCapabilityV1(reason="AUDIO_TEMP_RECOVERY_AMBIGUOUS")
    if not isinstance(auth, str) or not auth.strip():
        return AudioCapabilityV1(reason="GEMINI_AUTH_UNAVAILABLE")
    models = models or {}
    if (models.get("script") != SCRIPT_MODEL or models.get("tts") != TTS_MODEL):
        return AudioCapabilityV1(reason="GEMINI_MODEL_UNAVAILABLE")
    return AudioCapabilityV1(state="AVAILABLE", reason="READY", model=SCRIPT_MODEL)


def configured_audio_capability(config: Mapping | None = None, *, auth: str | None = None,
                                safe_root: bool = True) -> AudioCapabilityV1:
    """Render unavailable unless the localhost server supplies resolved auth state."""
    if config is None:
        from config_loader import load_config
        config = load_config()
    audio = config.get("audio_overview", {}) if isinstance(config, Mapping) else {}
    models = audio.get("models", {}) if isinstance(audio, Mapping) else {}
    return derive_audio_capability(auth=auth, models=models, safe_root=safe_root)


def audio_plan_status(capability: AudioCapabilityV1) -> dict:
    """Discriminated result for direct Audio planning (A6).

    `result` is REQUIRED on both variants so a client switches on one
    discriminator instead of inferring intent from the absence of a key, and so
    the frozen unknown-key rejection still applies. The unavailable variant is
    non-mutating: no operation, claim, or credential is created and no provider
    client is constructed.
    """
    if capability.state == "AVAILABLE":
        return {"schema": 1, "result": "PLANNED", "capability": capability.to_dict()}
    return {"schema": 1, "result": "FEATURE_UNAVAILABLE", "capability": capability.to_dict()}


def get_audio_css(accent, accent_dark, accent_bg):
    return f""".audio-bar {{ margin: .6rem 0 .2rem; }}
.audio-btn {{ background:{accent}; color:#fff; border:0; border-radius:20px; padding:.45rem 1rem; font:600 .85rem inherit; }}
.audio-btn:disabled {{ background:#bbb; cursor:not-allowed; }}
.audio-unavailable[hidden] {{ display:none; }}"""


def audio_modal_html(sub_text="Audio Overview is generated by the local server after approval."):
    return ("<div id=\"audio-modal-bg\" class=\"audio-modal-bg\" hidden aria-hidden=\"true\">"
            "<p>Audio Overview requires a server-issued approval.</p></div>")


AUDIO_JS = r"""
(function () {
  function capability() { return window._AUDIO_CAPABILITY || {state:"UNAVAILABLE", reason:"GEMINI_AUTH_UNAVAILABLE"}; }
  function applyAudioCapability() {
    var c = capability(), button = document.getElementById("audio-open"), notice = document.getElementById("audio-unavailable");
    if (!button) return;
    var ready = c.state === "AVAILABLE";
    button.disabled = !ready;
    button.setAttribute("aria-disabled", String(!ready));
    button.hidden = !ready;
    if (notice) { notice.hidden = ready; notice.textContent = ready ? "" : "Audio Overview unavailable: " + c.reason; }
  }
  window.openAudioModal = function () {
    var c = capability();
    // A6: same discriminated pair the server emits — clients switch on `result`.
    if (c.state !== "AVAILABLE") return {schema:1, result:"FEATURE_UNAVAILABLE", capability:c};
    return {schema:1, result:"PLANNED", capability:c};
  };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", applyAudioCapability);
  else applyAudioCapability();
})();
"""


def audio_script_block(_legacy_key=None, mode="paper", ctx=None, provider_js="", local_emails=None,
                       capability: AudioCapabilityV1 | Mapping | None = None):
    """Emit a capability-only script without probing credentials or serializing context."""
    if capability is None:
        capability = configured_audio_capability()
    if isinstance(capability, AudioCapabilityV1):
        capability = capability.to_dict()
    status = json.dumps(capability, ensure_ascii=False, separators=(",", ":"))
    return "<script>window._AUDIO_CAPABILITY=" + status + ";\n" + AUDIO_JS + "</script>"
