"""
배포 준비: PNG→WebP 변환 + API key strip + Cloudflare/gh-pages 배포.

아키텍처:
  - **로컬 docs/**: wrangler 배포 소스 (풀 콘텐츠)
  - **Cloudflare Workers**: `wrangler deploy` 로 직접 업로드. 실제 사용자
    콘텐츠. docs/.assetsignore 로 ai4s/scisci 등 로컬 전용 토픽 제외.
  - **GitHub gh-pages 브랜치**: 작은 리다이렉트 스텁만. github.io 에 접근한
    사용자를 Cloudflare 로 리다이렉트.
  - **GitHub master 브랜치**: 코드 + 설정만. docs/ 내 대용량 콘텐츠는
    .gitignore 로 제외.

Usage:
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s --quality 90    # WebP 품질 (기본 90)
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s --dry-run       # 변환 없이 크기 예상만
  PYTHONUTF8=1 python prepare_deploy.py --topic ai4s --push          # WebP 변환 + wrangler deploy + gh-pages 스텁 + master push

환경변수 (--push 시 필수):
  CLOUDFLARE_API_TOKEN (or CF_API_TOKEN) : Cloudflare Pages:Edit 권한
  CLOUDFLARE_ACCOUNT_ID                   : 계정 ID

단계:
  1. papers/*/figures/*.png → *.webp 변환 (quality 90)
  2. papers/*/index.html, review.md에서 .png → .webp 경로 업데이트
  3. {topic}/index.html에서 figure .png → .webp 업데이트 (타임라인 PNG는 유지)
  4. 원본 PNG 삭제 (WebP 검증된 것만)
  5. HTML 에서 API key 제거 (로컬 working tree 는 나중에 복원)
  6. (--push) `wrangler deploy` 로 Cloudflare 업로드
  7. (--push) gh-pages 브랜치에 리다이렉트 스텁 idempotent 동기화
  8. (--push) Cloudflare 엔드포인트 200 OK 검증
  9. (--push) master 에 코드/설정 변경만 commit + push (대용량 콘텐츠는 gitignored)
  10. 로컬 HTML 의 API key 복원
"""

import argparse
import os
import re
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from config_loader import get_github_branch, PAPERS_DIR as _PAPERS_DIR, DOCS_DIR, PROJECT_ROOT, get_topic_dir
PAPERS_DIR = str(_PAPERS_DIR)
REPO = str(PROJECT_ROOT)


def ensure_gitignore():
    """text.md를 .gitignore에 추가."""
    gi_path = os.path.join(REPO, ".gitignore")
    existing = ""
    if os.path.exists(gi_path):
        with open(gi_path, "r", encoding="utf-8") as f:
            existing = f.read()

    additions = []
    for pattern in ["papers/*/text.md", "__pycache__/", "_update_force_checkpoint.json",
                     "_regen_*.py", "_update_force.log"]:
        if pattern not in existing:
            additions.append(pattern)

    if additions:
        with open(gi_path, "a", encoding="utf-8") as f:
            f.write("\n# Auto-generated by prepare_deploy.py\n")
            for p in additions:
                f.write(f"{p}\n")
        print(f"  .gitignore: added {len(additions)} patterns")
    else:
        print("  .gitignore: already up to date")


MIN_VALID_WEBP_BYTES = 200  # anything smaller is almost certainly corrupt


def convert_png_to_webp(png_path, quality=90):
    """PNG → WebP 변환. 성공 시 (원본크기, 변환크기, webp_path) 반환.

    실패하거나 손상된 WebP (너무 작음)의 경우 dangling webp 파일을
    정리하고 None 을 반환해, 뒤따르는 Step 5 의 PNG 삭제 로직이
    원본을 실수로 지우지 않도록 한다."""
    webp_path = png_path.replace(".png", ".webp")
    try:
        from PIL import Image
        img = Image.open(png_path)
        img.save(webp_path, "WEBP", quality=quality)
        orig_size = os.path.getsize(png_path)
        webp_size = os.path.getsize(webp_path)
        if webp_size < MIN_VALID_WEBP_BYTES:
            raise RuntimeError(
                f"WebP output too small ({webp_size} bytes, likely corrupt)")
        return orig_size, webp_size, webp_path
    except Exception as e:
        print(f"  ERR: {png_path}: {e}")
        # Clean up any partial/corrupt webp file so Step 5 does not
        # treat it as a successful conversion and delete the PNG.
        if os.path.exists(webp_path):
            try:
                os.remove(webp_path)
            except Exception as cleanup_err:
                print(f"    (failed to clean dangling webp: {cleanup_err})")
        return 0, 0, None


def update_html_refs(file_path, fig_only=False):
    """HTML/MD 파일에서 figure .png → .webp 참조 업데이트."""
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    if fig_only:
        # 타임라인 PNG는 유지, figure 참조만 변환
        new_content = re.sub(r'(figures/[^"\']+)\.png', r'\1.webp', content)
    else:
        # 모든 .png → .webp (review.md, papers/*/index.html)
        new_content = re.sub(r'(figures/[^)\s"\']+)\.png', r'\1.webp', content)

    if new_content != content:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(new_content)
        return True
    return False


CF_BASE_URL = "https://paper-curation.jehyun-lee.workers.dev"
CF_PROBE_PATHS = ("/", "/humanoid/", "/physical-ai/", "/index.html")


def _verify_cloudflare(topic, timeout_s=300, interval_s=15):
    """Poll Cloudflare Worker endpoints until they all return 200 or timeout.

    We can't read a commit hash from response headers (Workers Static Assets
    don't expose one), so we only verify reachability + content size sanity.
    """
    import time as _time
    import urllib.request as _ur
    import urllib.error as _ue
    print(f"\n  [cf-verify] polling Cloudflare for ≤{timeout_s}s …")
    deadline = _time.time() + timeout_s
    last_status = {}
    while _time.time() < deadline:
        all_ok = True
        for path in CF_PROBE_PATHS:
            url = CF_BASE_URL + path
            try:
                req = _ur.Request(url, method="HEAD",
                                   headers={"User-Agent": "paper-curation/cf-verify"})
                resp = _ur.urlopen(req, timeout=10)
                code = resp.status
                size = resp.headers.get("content-length", "?")
                last_status[path] = (code, size)
                if code != 200:
                    all_ok = False
            except _ue.HTTPError as e:
                last_status[path] = (e.code, "?")
                all_ok = False
            except Exception as e:
                last_status[path] = ("err", str(e)[:60])
                all_ok = False
        if all_ok:
            print(f"  [cf-verify] all {len(CF_PROBE_PATHS)} endpoints 200 OK")
            for p, (c, s) in last_status.items():
                print(f"    {p}: {c} ({s} bytes)")
            return True
        _time.sleep(interval_s)
    print(f"  [cf-verify] TIMEOUT after {timeout_s}s — last status:")
    for p, (c, s) in last_status.items():
        print(f"    {p}: {c} ({s})")
    return False


_STUB_HTML = """<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url={cf_url}/{topic}/">
<title>{title} — Paper Curation</title>
<script>window.location.replace("{cf_url}/{topic}/");</script>
</head>
<body>
<p>Redirecting to <a href="{cf_url}/{topic}/">{title} — Paper Curation</a>...</p>
</body>
</html>
"""

_TOPIC_TITLES = {
    "humanoid": "Humanoid",
    "physical-ai": "Physical AI",
    "ai4s": "AI for Science",
    "scisci": "Science of Science",
}


def _discover_deployable_topics():
    """Scan docs/ for topic dirs deployed to Cloudflare (index.html present,
    not in .assetsignore, not the shared 'papers' repo)."""
    docs = str(DOCS_DIR)
    assetsignore = os.path.join(docs, ".assetsignore")
    excluded = {"papers", "notes"}
    if os.path.exists(assetsignore):
        with open(assetsignore, "r", encoding="utf-8") as f:
            for raw in f:
                line = raw.strip().rstrip("/")
                if line and not line.startswith("#") and "/" not in line:
                    excluded.add(line)
    topics = []
    for entry in os.listdir(docs):
        if entry.startswith(("_", ".")) or entry in excluded:
            continue
        full = os.path.join(docs, entry)
        if os.path.isdir(full) and os.path.isfile(os.path.join(full, "index.html")):
            topics.append(entry)
    return sorted(topics)


def _wrangler_env():
    """Build env for wrangler subprocess — accepts CF_API_TOKEN or
    CLOUDFLARE_API_TOKEN, maps the former to the latter for wrangler."""
    env = os.environ.copy()
    if "CLOUDFLARE_API_TOKEN" not in env and "CF_API_TOKEN" in env:
        env["CLOUDFLARE_API_TOKEN"] = env["CF_API_TOKEN"]
    missing = [k for k in ("CLOUDFLARE_API_TOKEN", "CLOUDFLARE_ACCOUNT_ID") if not env.get(k)]
    if missing:
        raise SystemExit(
            f"Missing env vars for wrangler: {', '.join(missing)}. "
            f"Set CF_API_TOKEN (or CLOUDFLARE_API_TOKEN) and CLOUDFLARE_ACCOUNT_ID."
        )
    return env


def _wrangler_deploy():
    """Run `npx wrangler deploy` from the repo root. Raises on failure."""
    env = _wrangler_env()
    print("\n  [wrangler] npx wrangler deploy ...")
    result = subprocess.run(
        ["npx", "wrangler", "deploy"],
        cwd=REPO, env=env,
        capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    if result.stdout:
        # Print last 15 lines for signal (upload summary, deploy URL)
        tail = "\n".join(result.stdout.splitlines()[-15:])
        print(f"  [wrangler stdout tail]\n{tail}")
    if result.returncode != 0:
        print(f"  [wrangler stderr]\n{result.stderr}")
        raise SystemExit(f"wrangler deploy failed with exit {result.returncode}")


def _sync_gh_pages_stubs(topics, cf_url=CF_BASE_URL):
    """Ensure origin/gh-pages has redirect stubs for each topic. Idempotent:
    only commits + pushes when a stub would actually change."""
    import tempfile
    print(f"\n  [gh-pages] syncing stubs for: {', '.join(topics)}")
    # Always fetch to ensure we act on the current remote state
    subprocess.run(["git", "fetch", "origin", "gh-pages"], check=True, cwd=REPO)
    worktree = tempfile.mkdtemp(prefix="paper-curation-ghpages-")
    try:
        subprocess.run(
            ["git", "worktree", "add", "--force", worktree, "gh-pages"],
            check=True, cwd=REPO,
        )
        changed = []
        for topic in topics:
            title = _TOPIC_TITLES.get(topic, topic.replace("-", " ").title())
            content = _STUB_HTML.format(cf_url=cf_url, topic=topic, title=title)
            stub_dir = os.path.join(worktree, topic)
            os.makedirs(stub_dir, exist_ok=True)
            stub_file = os.path.join(stub_dir, "index.html")
            need_write = True
            if os.path.exists(stub_file):
                with open(stub_file, "r", encoding="utf-8") as f:
                    if f.read() == content:
                        need_write = False
            if need_write:
                with open(stub_file, "w", encoding="utf-8", newline="\n") as f:
                    f.write(content)
                changed.append(topic)
        if not changed:
            print("  [gh-pages] all stubs up to date — no push needed")
            return
        subprocess.run(["git", "add", "-A"], check=True, cwd=worktree)
        msg = (
            f"Sync redirect stubs: {', '.join(changed)}\n\n"
            "Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"
        )
        subprocess.run(["git", "commit", "-m", msg], check=True, cwd=worktree)
        subprocess.run(["git", "push", "origin", "gh-pages"], check=True, cwd=worktree)
        print(f"  [gh-pages] pushed stub updates for: {', '.join(changed)}")
    finally:
        subprocess.run(
            ["git", "worktree", "remove", "--force", worktree],
            cwd=REPO, check=False,
        )


def main():
    parser = argparse.ArgumentParser(description="Prepare for GitHub Pages deployment")
    parser.add_argument("--topic", default="ai4s")
    parser.add_argument("--quality", type=int, default=90, help="WebP quality (1-100)")
    parser.add_argument("--dry-run", action="store_true", help="Estimate only, no conversion")
    parser.add_argument("--push", action="store_true", help="Git add + commit + push after conversion")
    parser.add_argument("--topics", nargs="+", help="Only deploy these topics (exclude others from git add)")
    parser.add_argument("--workers", type=int, default=8, help="Parallel workers for conversion")
    args = parser.parse_args()

    topic_dir = str(get_topic_dir(args.topic))

    # Step 1: .gitignore
    print("Step 1: .gitignore")
    if not args.dry_run:
        ensure_gitignore()

    # Step 2: Find all figure PNGs
    print("\nStep 2: Finding PNGs...")
    png_files = []
    for slug in os.listdir(PAPERS_DIR):
        fig_dir = os.path.join(PAPERS_DIR, slug, "figures")
        if not os.path.isdir(fig_dir):
            continue
        for f in os.listdir(fig_dir):
            if f.endswith(".png"):
                png_files.append(os.path.join(fig_dir, f))

    total_png_size = sum(os.path.getsize(f) for f in png_files)
    print(f"  Found {len(png_files)} PNGs ({total_png_size / 1048576:.0f} MB)")

    if args.dry_run:
        # Estimate: sample 10 files
        sample = png_files[:10]
        sample_orig = sum(os.path.getsize(f) for f in sample)
        sample_webp = 0
        for f in sample:
            orig, webp, _ = convert_png_to_webp(f, args.quality)
            sample_webp += webp
            # Clean up test webp
            wp = f.replace(".png", ".webp")
            if os.path.exists(wp):
                os.remove(wp)
        if sample_orig > 0:
            ratio = sample_webp / sample_orig
            est_total = total_png_size * ratio / 1048576
            print(f"\n  Estimated WebP size: {est_total:.0f} MB ({ratio:.0%} of original)")
            print(f"  Savings: {(total_png_size / 1048576) - est_total:.0f} MB")
        return

    # Step 3: Convert PNGs to WebP (parallel)
    print(f"\nStep 3: Converting to WebP (quality={args.quality})...")
    total_orig = 0
    total_webp = 0
    converted = 0

    with ThreadPoolExecutor(max_workers=args.workers) as executor:
        futures = {executor.submit(convert_png_to_webp, f, args.quality): f for f in png_files}
        for future in futures:
            orig, webp, webp_path = future.result()
            if webp_path:
                total_orig += orig
                total_webp += webp
                converted += 1

    print(f"  Converted: {converted}/{len(png_files)}")
    print(f"  {total_orig / 1048576:.0f} MB → {total_webp / 1048576:.0f} MB "
          f"({total_webp / max(1, total_orig):.0%})")

    # Step 4: Update HTML/MD references (.png → .webp where .webp exists)
    # Always run regardless of PNG conversion count — HTML may have been
    # regenerated with .png refs after a previous PNG→WebP conversion.
    print("\nStep 4: Updating references...")
    updated = 0
    for slug in os.listdir(PAPERS_DIR):
        slug_dir = os.path.join(PAPERS_DIR, slug)
        if not os.path.isdir(slug_dir):
            continue
        # Only update if .webp figures actually exist
        fig_dir = os.path.join(slug_dir, "figures")
        has_webp = os.path.isdir(fig_dir) and any(f.endswith(".webp") for f in os.listdir(fig_dir))
        if not has_webp:
            continue
        for fname in ["index.html", "review.md"]:
            fpath = os.path.join(slug_dir, fname)
            if os.path.exists(fpath) and update_html_refs(fpath):
                updated += 1

    # Update topic index.html (figures only, keep timeline PNGs)
    topic_index = os.path.join(topic_dir, "index.html")
    if os.path.exists(topic_index) and update_html_refs(topic_index, fig_only=True):
        updated += 1

    print(f"  Updated: {updated} files")

    # Step 5: Delete original PNGs (only when WebP is verifiably good).
    # Double-defense against WebP-conversion races: we require the WebP
    # to actually exist AND to be at least MIN_VALID_WEBP_BYTES, which
    # catches cases where Pillow crashed halfway and left a tiny or
    # corrupt output. Any PNG preserved by this guard is logged so the
    # operator can investigate and retry.
    print("\nStep 5: Deleting original PNGs...")
    deleted = 0
    preserved = 0
    for png_path in png_files:
        webp_path = png_path.replace(".png", ".webp")
        if not os.path.exists(webp_path):
            preserved += 1
            print(f"  KEEP: {png_path} (no WebP)")
            continue
        webp_size = os.path.getsize(webp_path)
        if webp_size < MIN_VALID_WEBP_BYTES:
            preserved += 1
            print(f"  KEEP: {png_path} (WebP too small: {webp_size} bytes)")
            continue
        os.remove(png_path)
        deleted += 1
    print(f"  Deleted: {deleted} PNGs, Preserved: {preserved}")

    # Step 6: Strip API keys from HTML for deploy (local working tree restored after commit)
    print("\nStep 6: Stripping API keys from deployed HTML (local keys preserved)...")
    import re as _re
    _originals = {}  # Path -> original content, restored after push
    for html_path in DOCS_DIR.rglob("index.html"):
        text = html_path.read_text(encoding="utf-8")
        new_text = _re.sub(
            r'(const|let|var)\s+_ANTHROPIC_KEY\s*=\s*"sk-[^"]*"',
            r'\1 _ANTHROPIC_KEY = ""',
            text,
        )
        new_text = _re.sub(
            r'(const|let|var)\s+_OPENAI_KEY\s*=\s*"sk-[^"]*"',
            r'\1 _OPENAI_KEY = ""',
            new_text,
        )
        if new_text != text:
            _originals[html_path] = text
            html_path.write_text(new_text, encoding="utf-8")

    def _restore_originals():
        for p, orig in _originals.items():
            p.write_text(orig, encoding="utf-8")

    # Safety net: verify no residual API keys remain in any deployed HTML
    _leak_paths = [
        str(p) for p in DOCS_DIR.rglob("index.html")
        if _re.search(r'sk-(ant|proj)-[A-Za-z0-9_\-]{10,}', p.read_text(encoding="utf-8"))
    ]
    if _leak_paths:
        _restore_originals()
        print(f"  ABORT: API key still present in {len(_leak_paths)} files — refusing to commit:")
        for p in _leak_paths:
            print(f"    - {p}")
        sys.exit(1)
    print(f"  Stripped API keys from {len(_originals)} files (0 leaks remaining)")

    # Step 7-10: Deploy (only if --push). Otherwise we stop here — the
    # working tree was modified by API-key strip in Step 6 so we still
    # need to restore it in the finally block.
    try:
        if not args.push:
            print("\n(--push 없이 실행됨. Cloudflare 업로드/gh-pages 동기화/master push 모두 스킵)")
        else:
            # Step 7: Upload full content to Cloudflare via wrangler
            print("\nStep 7: Deploying to Cloudflare (wrangler deploy)...")
            _wrangler_deploy()

            # Step 8: Ensure gh-pages has redirect stubs for every deployed topic
            topics_for_stubs = args.topics or _discover_deployable_topics()
            if topics_for_stubs:
                print(f"\nStep 8: Syncing gh-pages redirect stubs "
                      f"({len(topics_for_stubs)} topics)...")
                _sync_gh_pages_stubs(topics_for_stubs)
            else:
                print("\nStep 8: No deployable topics found — skipping gh-pages sync")

            # Step 9: Verify Cloudflare endpoints return 200
            print("\nStep 9: Verifying Cloudflare endpoints...")
            _verify_cloudflare(args.topic)

            # Step 10: Commit + push master — only code/config changes.
            # docs/* content is gitignored, so this only captures genuine
            # source changes (pipeline scripts, wrangler.toml, etc.).
            print("\nStep 10: Committing code/config changes to master...")
            os.chdir(REPO)
            subprocess.run(["git", "add", "-A"], check=True)
            staged = subprocess.run(
                ["git", "diff", "--cached", "--quiet"], capture_output=True,
            )
            if staged.returncode == 0:
                print("  No master-tracked changes to commit")
            else:
                name_status = subprocess.run(
                    ["git", "diff", "--cached", "--name-status"],
                    capture_output=True, text=True, encoding="utf-8", errors="replace",
                )
                ns_lines = [l for l in (name_status.stdout or "").splitlines() if l.strip()]
                print(f"  Master-tracked diff: {len(ns_lines)} files")
                for l in ns_lines[:15]:
                    print(f"    {l}")
                if len(ns_lines) > 15:
                    print(f"    ... +{len(ns_lines) - 15} more")
                subprocess.run(
                    ["git", "commit", "-m",
                     f"Deploy: {converted} figures WebP, "
                     f"{total_orig // 1048576}→{total_webp // 1048576}MB\n\n"
                     f"Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"],
                    check=True,
                )
                subprocess.run(["git", "push", "origin", "master"], check=True)
                print("  Pushed code/config changes to master")
    finally:
        # Restore local working tree so Deep Research UI keeps working without rebuild
        _restore_originals()
        if _originals:
            print(f"  Restored {len(_originals)} local HTML files (API keys preserved for local dev)")

    print(f"\nDone! Total savings: {(total_orig - total_webp) / 1048576:.0f} MB")


if __name__ == "__main__":
    main()
